name: tfl_pipeline
version: "1.0.0"
config-version: 2
profile: tfl_pipeline
model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  tfl_pipeline:
    raw:
      +materialized: view
      +schema: raw
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
